# Generated by Django 3.0.5 on 2021-08-19 06:54

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=40)),
                ('stud_class', models.PositiveIntegerField()),
                ('department', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['name', 'roll_no', 'stud_class', 'department'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student_Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_subject', to='blog_posts.Student')),
            ],
            options={
                'ordering': ['student', 'subject'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mob_no', phonenumber_field.modelfields.PhoneNumberField(help_text='Contact phone number', max_length=128, region=None)),
                ('address', models.CharField(max_length=40)),
                ('father_name', models.CharField(max_length=20)),
                ('mother_name', models.CharField(max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_details', to='blog_posts.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Book_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=30)),
                ('student', models.ManyToManyField(related_name='book_list', to='blog_posts.Student')),
            ],
            options={
                'ordering': ['book_name'],
                'managed': True,
            },
        ),
    ]
