# Generated by Django 3.0.5 on 2021-08-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'managed': True, 'ordering': ['id', 'name', 'roll_no', 'stud_class', 'department']},
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
