# Generated by Django 3.0.5 on 2021-08-21 13:08

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0002_auto_20210821_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='father_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='mob_no',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Contact phone number', max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='mother_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
