# Generated by Django 3.0.5 on 2021-08-17 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(max_length=20)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_subject', to='myapp.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Student_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mob_no', models.IntegerField(max_length=10)),
                ('address', models.TextField()),
                ('father_name', models.TextField(max_length=20)),
                ('mother_name', models.TextField(max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_details', to='myapp.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Book_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.TextField(max_length=30)),
                ('student', models.ManyToManyField(related_name='book_list', to='myapp.Student')),
            ],
        ),
    ]
