# Generated by Django 3.0.5 on 2021-08-18 09:20

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210818_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='mob_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, region=None),
        ),
    ]
